### ISSUE TITLE
Validators are only setting weights for the lowest UIDs

### ISSUE THREAD

**Issue by Synweigh** [UncleTensor/BittAudio#1]
Hi, I already talked to one of the devs about this and he thought I should open an issue here.

On line 300 of the validator the scores are being set incorrectly. 

### Issue:
Validators select a subset of the miners to query each iteration like this:
```python
zipped_uids = list(zip(uids, queryable_uids))
filtered_uids = list(zip(*filter(lambda x: x[1], zipped_uids)))[0]
bt.logging.info(f"filtered_uids:{filtered_uids}")
dendrites_to_query = random.sample( filtered_uids, min( dendrites_per_query, len(filtered_uids) ) )
```

This yields a subset of miners (say 14 of 256). After these miners have been queried their responses are handled like this:
```python
for i, resp_i in enumerate(responses): 
```
This will yield index numbers in a range from 0 to 13. Scores are then calculated. So far there is no issue. However, when the scores are set they are set like this:
```python
scores[i] = config.alpha * scores[i] + (1 - config.alpha) * score
```
Because the scores vector is of size 256 (which it should be) and i is one of the numbers from 0 to 13 (note: not the uid) the score will be set for the incorrect miner, i.e. one of the miners with uid 0 to 13. This leads to the weights being set incorrectly. It is evident from the distribution of incentive that this is the case as the only miners which have emission that is not the "base" emission are miners with uid 0-13, see [taostats](https://taostats.io/subnets/netuid-16/). 

As I do not have privileges for this repo I cannot make a pull request with a suggested solution. I would however be happy to explain the issue further. Feel free to contact me on Discord (same username).

**Comment by Shaukat-Hussain** [comment]
Hi, thanks for the suggestion. The issue has been identified and fixed with this code:
`                                    uid_index = uids.index(filtered_axons[i].uid)
                                    scores[uid_index] = config.alpha * scores[uid_index] + (1 - config.alpha) * score`
Best Regards

**Comment by Shaukat-Hussain** [comment]
Hi,
Thanks for identifying this issue. The suggested code to fix it:
```
uid_index = uids.index(filtered_axons[i].uid)
scores[uid_index] = config.alpha * scores[uid_index] + (1 - config.alpha) * score
```
Let us know your thoughts.
BR,

**Comment by IamHussain503** [comment]
Hi Thanks for openning this issue, the problem has been identified and fixed:

```
zipped_uids = list(zip(uids, metagraph.axons))
uid_index = list(zip(*filter(lambda x: x[1] == iax, zipped_uids)))[0][0]
scores[uid_index] = config.alpha * scores[uid_index] + (1 - config.alpha) * score
```

Let us know your thoughts.
Best Regards

**Comment by IamHussain503** [comment]
The issue will be closed as problem has been identified and resolved. Thanks for your support.
